"""empty message

Revision ID: f39c3de44071
Revises: fbcc0cc61aa9
Create Date: 2017-08-22 17:11:29.903620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39c3de44071'
down_revision = 'fbcc0cc61aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kickoff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papresults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('patientNumber', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('lmp', sa.String(), nullable=True),
    sa.Column('adequateSample', sa.Integer(), nullable=False),
    sa.Column('cellCount', sa.String(), nullable=False),
    sa.Column('endocervicalCells', sa.Integer(), nullable=False),
    sa.Column('metaplasticCells', sa.Integer(), nullable=True),
    sa.Column('backgroundInflammation', sa.String(), nullable=False),
    sa.Column('fungal', sa.Integer(), nullable=False),
    sa.Column('trich', sa.Integer(), nullable=False),
    sa.Column('hpv', sa.Integer(), nullable=False),
    sa.Column('bacteria', sa.Integer(), nullable=False),
    sa.Column('hsv', sa.Integer(), nullable=False),
    sa.Column('impression', sa.String(), nullable=False),
    sa.Column('advice', sa.String(), nullable=False),
    sa.Column('doctor', sa.String(), nullable=False),
    sa.Column('disposition', sa.String(), nullable=False),
    sa.Column('kickoff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kickoff_id'], ['kickoff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('papresults')
    op.drop_table('kickoff')
    # ### end Alembic commands ###
