"""empty message

Revision ID: fc72cd6d7758
Revises: 7c51907404ea
Create Date: 2017-08-22 16:22:16.555517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc72cd6d7758'
down_revision = '7c51907404ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papresults', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papresults', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
